AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'trip-diegoclimaites

  Rest API to manage a Trips for yourself

  '
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: TripTable
        ENDPOINT_OVERRIDE: ''
Resources:
  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dclimaites-trips/fafdfe86a1eead97e7e45ebed33a68fe
      Handler: br.fiap.diegoclimaites.trip.handler.CreateTripRecord::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        CreateTripRecord:
          Type: Api
          Properties:
            Path: /trip
            Method: post
  GetTripRecordByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dclimaites-trips/fafdfe86a1eead97e7e45ebed33a68fe
      Handler: br.fiap.diegoclimaites.trip.handler.GetTripRecordByPeriodFunction::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        GetTripRecordsByPeriod:
          Type: Api
          Properties:
            Path: /trips
            Method: get
            RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
  GetTripRecordByCountryAndCityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dclimaites-trips/fafdfe86a1eead97e7e45ebed33a68fe
      Handler: br.fiap.diegoclimaites.trip.handler.GetTripRecordByCountryAndCityFunction::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        GetTripRecordByCountryFunction:
          Type: Api
          Properties:
            Path: /trips/{country}/
            Method: get
            RequestParameters:
            - method.request.querystring.city
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
      - AttributeName: country
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: city
        AttributeType: S
      - AttributeName: reason
        AttributeType: S
      KeySchema:
      - AttributeName: country
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: cityIndex
        KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: city
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: reasonIndex
        KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: reason
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
Outputs:
  CreateTripRecordFunction:
    Description: CreateTripRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripRecordFunction
      - Arn
  GetTripRecordByPeriodFunction:
    Description: GetTripRecordByPeriodFunction Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordByPeriodFunction
      - Arn
  GetTripRecordByCountryAndCityFunction:
    Description: GetTripRecordByCountryAndCityFunction Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordByCountryAndCityFunction
      - Arn
